# Generated by Django 2.1.1 on 2018-09-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_code', models.AutoField(primary_key=True, serialize=False)),
                ('area_text', models.CharField(max_length=50, verbose_name='Area Block')),
            ],
            options={
                'ordering': ('area_code',),
            },
        ),
        migrations.CreateModel(
            name='class_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ('gr_no',),
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_code', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('class_code',),
            },
        ),
        migrations.CreateModel(
            name='gardian',
            fields=[
                ('family_id', models.IntegerField(primary_key=True, serialize=False)),
                ('father_name', models.CharField(max_length=50, verbose_name="Father's Name")),
                ('father_profession', models.CharField(max_length=50, verbose_name="Father's Occupation")),
                ('father_cell', models.CharField(max_length=50, verbose_name="Father's Cell Number")),
                ('mother_name', models.CharField(max_length=50, verbose_name="Mother's Name")),
                ('mother_cell', models.CharField(max_length=50, verbose_name="Mother's Cell Number")),
            ],
            options={
                'ordering': ('family_id',),
            },
        ),
        migrations.CreateModel(
            name='gr_register',
            fields=[
                ('gr_no', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('FM', 'Female')], max_length=10)),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Home Adress')),
                ('area_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Area', verbose_name='Area')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_C', to='students.Classes', verbose_name='Current Class')),
                ('classes_A', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes_A', to='students.Classes', verbose_name='Class of Admission')),
            ],
            options={
                'ordering': ('gr_no',),
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('section_code', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('section_code',),
            },
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('session_code', models.AutoField(primary_key=True, serialize=False)),
                ('session_years', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('session_code',),
            },
        ),
        migrations.AddField(
            model_name='gr_register',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_C', to='students.Sections', verbose_name='Current Section'),
        ),
        migrations.AddField(
            model_name='gr_register',
            name='sections_A',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections_A', to='students.Sections', verbose_name='Section of Admission'),
        ),
        migrations.AddField(
            model_name='gardian',
            name='gr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.gr_register'),
        ),
        migrations.AddField(
            model_name='class_register',
            name='class_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Classes'),
        ),
        migrations.AddField(
            model_name='class_register',
            name='gr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.gr_register'),
        ),
        migrations.AddField(
            model_name='class_register',
            name='section_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Sections'),
        ),
        migrations.AddField(
            model_name='class_register',
            name='session_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.session'),
        ),
    ]
