# Generated by Django 2.1.1 on 2018-09-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gr_register',
            name='gr_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
