# Generated by Django 2.1.1 on 2018-09-18 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20180918_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='gr_register',
            name='family_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.gardian', verbose_name='Family ID'),
        ),
        migrations.AlterField(
            model_name='gardian',
            name='gr_no',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.gr_register'),
        ),
    ]
