# Generated by Django 2.1.1 on 2018-09-18 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20180918_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardian',
            name='gr_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.gr_register'),
        ),
    ]
