# Generated by Django 2.1.1 on 2018-09-18 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20180918_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gr_register',
            name='family_id',
        ),
        migrations.AlterField(
            model_name='gardian',
            name='gr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.gr_register'),
        ),
    ]
