# Generated by Django 2.1.1 on 2018-09-19 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20180918_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_register',
            name='class_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Classes', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='class_register',
            name='gr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.gr_register', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='class_register',
            name='roll_no',
            field=models.IntegerField(null=True, verbose_name='Roll No'),
        ),
        migrations.AlterField(
            model_name='class_register',
            name='section_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Sections', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='class_register',
            name='session_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.session', verbose_name='Session'),
        ),
    ]
