# Generated by Django 2.1.2 on 2018-10-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20180919_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gr_register',
            old_name='classes',
            new_name='classes_C',
        ),
        migrations.RenameField(
            model_name='gr_register',
            old_name='sections',
            new_name='sections_C',
        ),
    ]
