# Generated by Django 2.1.2 on 2018-10-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20181011_1602'),
        ('fees', '0002_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='Gr_num',
            field=models.ForeignKey(default=231, on_delete=django.db.models.deletion.CASCADE, to='students.gr_register'),
        ),
    ]
