# Generated by Django 2.1.2 on 2018-10-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_fee_fee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fee_dues',
            field=models.BigIntegerField(default=1000),
        ),
    ]
