# Generated by Django 2.1.2 on 2018-10-17 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_fee_fee_dues'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='paid_source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fees.fees_source'),
        ),
    ]
