# Generated by Django 2.1.2 on 2018-10-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20181011_1602'),
        ('fees', '0006_fee_paid_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='class_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.Classes'),
        ),
        migrations.AddField(
            model_name='fee',
            name='paid',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=1),
        ),
    ]
