# Generated by Django 2.1.2 on 2018-10-17 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20181011_1602'),
        ('fees', '0007_auto_20181017_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='guradian_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.gardian'),
        ),
    ]
