# Generated by Django 2.1.2 on 2018-10-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_fee_guradian_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='fee_amount_dues',
        ),
    ]
