# Generated by Django 2.1.2 on 2018-10-20 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_fee_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='paid_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
